### PR TITLE
Remove dependency on termion. Reformat using cargo fmt

### PR DESCRIPTION
**Pull request by felipecsl**
The dependency on termion makes it so that scarlet cannot be compiled targeting web assembly.
I'm not super familiar with the reasons why that's the case or how one could work around that limitation, but this didn't seem to be necessary as that code seemed to be used mostly in ignored unit tests.
I've removed the dependency, the methods that were using it and reformatted the code with `cargo fmt`.
Snippet with error output from `wasm-pack`:
```
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/lib.rs:27:9
   |
27 | pub use sys::tty::{is_tty, get_tty};
   |         ^^^ maybe a missing crate `sys`?

error[E0433]: failed to resolve: maybe a missing crate `sys`?
 --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/async.rs:5:5
  |
5 | use sys::tty::get_tty;
  |     ^^^ maybe a missing crate `sys`?

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:29:5
   |
29 | use sys::attr::{get_terminal_attr, raw_terminal_attr, set_terminal_attr};
   |     ^^^ maybe a missing crate `sys`?

error[E0432]: unresolved import `sys`
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:28:5
   |
28 | use sys::Termios;
   |     ^^^ maybe a missing crate `sys`?

error[E0425]: cannot find function `get_tty` in this scope
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/async.rs:14:36
   |
14 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
   |                                    ^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_tty` in this scope
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/async.rs:43:36
   |
43 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
   |                                    ^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:45:9
   |
45 |         set_terminal_attr(&self.prev_ios).unwrap();
   |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_terminal_attr` in this scope
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:90:23
   |
90 |         let mut ios = get_terminal_attr()?;
   |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `raw_terminal_attr` in this scope
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:93:9
   |
93 |         raw_terminal_attr(&mut ios);
   |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
  --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:95:9
   |
95 |         set_terminal_attr(&ios)?;
   |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:107:9
    |
107 |         set_terminal_attr(&self.prev_ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_terminal_attr` in this scope
   --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:113:23
    |
113 |         let mut ios = get_terminal_attr()?;
    |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `raw_terminal_attr` in this scope
   --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:114:9
    |
114 |         raw_terminal_attr(&mut ios);
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> /Users/felipecsl/.cargo/registry/src/github.com-1ecc6299db9ec823/termion-1.5.5/src/raw.rs:115:9
    |
115 |         set_terminal_attr(&ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 15 previous errors
```

### CODE REVIEW

**Comment by nicholas-miklaucic** [comment]
First, I'd like to apologize for not getting back to you sooner! I thought I had set notifications for this but apparently that wasn't the case.

The reason `termion` is currently used is to allow you to print colors to the terminal. I used this a lot when doing tests, because it's the only way to actually see what's going on instead of staring at coordinate values. (That's why the tests are ignored, because they're visual checks.) 

I'm a little loath to completely remove those tests and functionality, because I think it's useful for visually seeing the effects of things, but I completely understand that WASM support is more important: I'm working on a website that uses this now, so it's good timing. Given that, I'll try and put it behind a cargo feature: will that allow it to be used in WASM? 

I'm also not going to agree with your auto-formatter in all of the cases it changed stuff. Given both of those things, it'll take me a day or two to merge this. Does that work?

**Comment by felipecsl** [comment]
No worries, thanks for your thoughtful response!

**Comment by nicholas-miklaucic** [comment]
Merged in https://github.com/nicholas-miklaucic/scarlet/commit/761d42168657b70a1d21a94aced3917eb06b0118. I'll publish it shortly to crates.io. Does this fix the wasm-pack issues?

**Comment by felipecsl** [comment]
thank you!

**Pull request closed without merging**
